[package]
name = "d"
version = "0.1.0"
edition = "2021"

[dependencies]
yt-dlp = { version = "^1.2.3", features = ["tracing"] }
tokio = { version = "^1.0", features = ["full"] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3